[package]
name = "robot-rate-calculator"
version = "0.0.0"
authors = ["Li Honghao <honghao@comp.nus.edu.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4"